# Tuple Solutions: Practice Exercises & Challenges

### 1. Solution(s): Access Elements in a Tuple

In [ ]:
# 1.1. A negative index larger than the tuple length raises an IndexError.
the_tuple = (1, 2, 3)
print(the_tuple[-5])

# 1.2.Slicing with out-of-bounds indices does not raise an error; it returns all available elements within the range.
the_tuple = (1, 2, 3)
print(the_tuple[1:10]) 

# 1.3. Attempting to access an element raises an IndexError.
empty_tuple = ()
print(empty_tuple[0])

# 1.4. Access specific elements by chaining indexing.
nested_tuple = ((1, 2), (3, 4))
print(nested_tuple[1][1])

# 1.5. 
the_tuple = (10, 20, 30, 40)
try:
    print(the_tuple[10])  # Invalid index
except IndexError:
    print("Index out of range")

### 2. Solution(s): Convert Tuple to List and Vice Versa

In [ ]:
# 2.1.Convert (10, 20, 30) to [10, 20, 30], add 40, and revert it to (10, 20, 30, 40).
the_tuple = (10, 20, 30)
the_list = list(the_tuple)
the_list.append(40)
the_tuple = tuple(the_list)
print(the_tuple)

# 2.2. Use tuple([100, 200, 300]) to get (100, 200, 300).
the_tuple = tuple([100, 200, 300])
print(the_tuple)

# 2.3. Convert ((1, 2), (3, 4)) to [[1, 2], [3, 4]], modify it to [[1, 2, 5], [3, 4]],
    # and revert to ((1, 2, 5), (3, 4)).
nested_tuple = ((1, 2), (3, 4))
nested_list = [list(inner) for inner in nested_tuple] 
nested_list[0].append(5)  
nested_tuple = tuple(tuple(inner) for inner in nested_list)  
print(nested_tuple)  


# 2.4. Convert () to [], add [1, 2, 3], and revert to (1, 2, 3).
empty_tuple = ()
empty_list = list(empty_tuple)
empty_list.extend([1, 2, 3]) 
empty_tuple = tuple(empty_list)
print(empty_tuple)

# 2.5. Start with (5, 6, 7), add 8 and 9, remove 6, and end with (5, 7, 8, 9).
the_tuple = (5, 6, 7)
the_list = list(the_tuple)
the_list.extend([8, 9])  
the_list.remove(6)  
the_tuple = tuple(the_list)
print(the_tuple)

### 3. Solution(s): Count and Index Methods for Tuples

In [ ]:
# 3.1. count() returns 3. index() returns 10
the_tuple = (5, 5, 5, 10, 15)
print(the_tuple.count(5))  
print(the_tuple.index(10))  


# 3.2. count() returns 2. index() returns 3.
the_tuple = ('cat', 'dog', 'cat', 'bird')
print(the_tuple.count('cat')) 
print(the_tuple.index('bird')) 


# 3.3. It raises a ValueError for index() when the value is not found.
the_tuple = (1, 2, 3)
try:
    print(the_tuple.index(4))  
except ValueError:
    print("Value not found")


# 3.4. count() returns 3. index() returns 3.
the_tuple = (1, 'a', 1, 'b', 1)
print(the_tuple.count(1))  
print(the_tuple.index('b'))  

# 3.5. count() returns 0. index() raises a ValueError.
the_tuple = ()
print(the_tuple.count(1)) 
try:
    print(the_tuple.index(1)) 
except ValueError:
    print("Value not found")

### 4. Solution(s): Concatenate and Repeat Tuples

In [ ]:
# 4.1. Expected output: (10, 20, 30, 40, 50)
tuple1 = (10, 20)
tuple2 = (30, 40, 50)
combined = tuple1 + tuple2
print(combined) 

# 4.2. Expected output: ('x', 'y', 'x', 'y', 'x', 'y', 'x', 'y', 'x', 'y')
tuple1 = ('x', 'y')
repeated = tuple1 * 5
print(repeated)  

# 4.3. Expected output: (42, 50, 60, 42, 50, 60)
single_tuple = (42,)  # Single-element tuple
combined = single_tuple + (50, 60)
repeated = combined * 2
print(repeated)  

# 4.4. Expected output: (1, 'a', 2, 'b', 1, 'a', 2, 'b', 1, 'a', 2, 'b')
tuple1 = (1, 'a')
tuple2 = (2, 'b')
combined = tuple1 + tuple2
repeated = combined * 3
print(repeated)  


# 4.5. Expected output: (1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3)
empty_tuple = ()
tuple1 = (1, 2, 3)
combined = empty_tuple + tuple1
repeated = combined * 4
print(repeated)

### 5.  Solution(s): Unpack Elements from a Tuple

In [ ]:
# 5.1. Expected output: 5 10 15 20
the_tuple = (5, 10, 15, 20)
a, b, c, d = the_tuple
print(a, b, c, d)  

# 5.2.  Expected output: 100 [200, 300, 400] 500
the_tuple = (100, 200, 300, 400, 500)
a, *b, c = the_tuple
print(a, b, c) 

# 5.3. Expected output: 1 2 3 4
the_tuple = ((1, 2), 3, 4)
(x, y), z, w = the_tuple
print(x, y, z, w)  

# 5.4.  Expected output: 10 20 [30, 40, 50]
the_tuple = (10, 20, 30, 40, 50)
a, b, *rest = the_tuple
print(a, b, rest) 

# 5.5. Output: Error: too many values to unpack (expected 2)
the_tuple = (1, 2, 3)
try:
    a, b = the_tuple  # Mismatch in the number of variables
except ValueError as e:
    print("Error:", e)

### 6. Solution(s): Check if an Element Exists in a Tuple

In [ ]:
# 6.1. The result is Found.
the_tuple = (10, 20, 30, 40)
if 30 in the_tuple:
    print("Found") 
else:
    print("Not Found")


# 6.2. The result is Found.
the_tuple = ('cat', 'dog', 'bird')
# Standard
if 'dog' in the_tuple:
    print("Found")  # Output: Found
else:
    print("Not Found")

# Optimized
result = "Found" if 'dog' in the_tuple else "Not Found"
print(result)  # Output: Found


# 6.3. The result is Not Found.
the_tuple = (1, 2, 3, 4)
if 5 not in the_tuple:
    print("Not Found") 

    
# 6.4. The result is Not Found.
the_tuple = ()
if 1 in the_tuple:
    print("Found")
else:
    print("Not Found") 


# 6.5. The result is Found.
the_tuple = (100, 200, 300)
value = int(input("Enter a number: "))  # Assume user enters 200
result = "Found" if value in the_tuple else "Not Found"
print(result)  # Expected output: Found

### 7. Solution(s): Slice a Tuple

In [ ]:
# 7.1. Expected output: (3, 4, 5)
the_tuple = (1, 2, 3, 4, 5, 6)
print(the_tuple[2:5])  

# 7.2. Expected output: (40, 50)
the_tuple = (10, 20, 30, 40, 50)
print(the_tuple[-2:])  

# 7.3. Expected output: (5, 20)
the_tuple = (5, 10, 15, 20, 25, 30)
print(the_tuple[::3])  

# 7.4. Expected output: (500, 400, 300, 200, 100)
the_tuple = (100, 200, 300, 400, 500)
print(the_tuple[::-1])  

# 7.5. Expected output: ()
the_tuple = (7, 8, 9)
print(the_tuple[1:1])

### 8. Solution(s): Compare Two Tuples

In [ ]:
# 8.1. Output: False, Output: True
tuple1 = (5, 10, 15)
tuple2 = (5, 10, 20)
print(tuple1 == tuple2) 
print(tuple1 < tuple2)  

# 8.2. Output: False, Output: True
tuple1 = ((1, 2), 3)
tuple2 = ((1, 2), 4)
print(tuple1 == tuple2) 
print(tuple1 < tuple2)  

# 8.3. Output: False, Output: False
tuple1 = (1, 2, 3)
tuple2 = (1, 2)
print(tuple1 == tuple2)
print(tuple1 < tuple2)  

# 8.4. Output: True
tuple1 = (1, 'a', 3)
tuple2 = (1, 'b', 3)
print(tuple1 < tuple2)  


# 8.5. Output: True
tuple1 = ()
tuple2 = (1,)
print(tuple1 < tuple2)

### 9. Solution(s): Iterate Over a Tuple

In [ ]:
# 9.1. Expected output:
# 1
# 2
# 3
# 4
the_tuple = (1, 2, 3, 4)
for elem in the_tuple:
    print(elem)

# 9.2. Expected output:
# Index 0: 5
# Index 1: 10
# Index 2: 15
# Index 3: 20
the_tuple = (5, 10, 15, 20)
for index, elem in enumerate(the_tuple):
    print(f"Index {index}: {elem}")
    
    
# 9.3. Expected output:
# (1, 2)
# (3, 4)
# (5, 6)
the_tuple = ((1, 2), (3, 4), (5, 6))
for sub_tuple in the_tuple:
    print(sub_tuple)
    
# 9.4. Expected output:
# 25
# 30
the_tuple = (10, 15, 20, 25, 30)
for elem in the_tuple:
    if elem > 20:
        print(elem)
        
# 9.5. Expected output: (No output since the tuple is empty)
the_tuple = ()
for elem in the_tuple:
    print(elem)

### 10. Solution(s): Sort Elements of a Tuple

In [ ]:
# 10.1. Expected output: (5, 7, 8, 9)
the_tuple = (9, 7, 8, 5)
sorted_tuple = tuple(sorted(the_tuple))
print(sorted_tuple)  

# 10.2. Expected output: (9, 6, 3, 1)
the_tuple = (6, 3, 9, 1)
sorted_tuple = tuple(sorted(the_tuple, reverse=True))
print(sorted_tuple)  


# 10.3. Expected output: ('apple', 'banana', 'cherry'),  Expected output: ('cherry', 'banana', 'apple')
the_tuple = ('banana', 'apple', 'cherry')

# Alphabetical order
sorted_tuple = tuple(sorted(the_tuple))
print(sorted_tuple)  


# Reverse alphabetical order
sorted_tuple_desc = tuple(sorted(the_tuple, reverse=True))
print(sorted_tuple_desc)  


# 10.4. Expected output: Error: '<' not supported between instances of 'str' and 'int'
the_tuple = (1, 'apple', 2, 'banana')
try:
    sorted_tuple = tuple(sorted(the_tuple))
except TypeError as e:
    print("Error:", e)  
    

 # 10.5. Expected output: ()
the_tuple = ()
sorted_tuple = tuple(sorted(the_tuple))
print(sorted_tuple)